### ISSUE TITLE
i think i should report this

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [Interlink-Media/Sierra#27]
[03:10:16 WARN]: [net.square.sierra.packetevents.api.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 0, cap: 256)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.netty.buffer.ByteBufOperatorModernImpl.readByte(ByteBufOperatorModernImpl.java:74) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.netty.buffer.ByteBufHelper.readByte(ByteBufHelper.java:67) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.wrapper.PacketWrapper.readByte(PacketWrapper.java:349) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.wrapper.PacketWrapper.readVarInt(PacketWrapper.java:389) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.wrapper.PacketWrapper.readItemStackModern(PacketWrapper.java:461) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.wrapper.PacketWrapper.readItemStack(PacketWrapper.java:498) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/de.feelix.sierra.check.impl.book.BookValidation.handlePickItem(BookValidation.java:138) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/de.feelix.sierra.check.impl.book.BookValidation.handle(BookValidation.java:60) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/de.feelix.sierra.check.CheckManager.processAvailableChecksReceive(CheckManager.java:47) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/de.feelix.sierra.listener.PacketReceiveListener.onPacketReceive(PacketReceiveListener.java:63) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.event.PacketReceiveEvent.call(PacketReceiveEvent.java:44) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.event.EventManager.callEvent(EventManager.java:84) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:84) ~[Sierra-1.5.0.jar:?]
        at Sierra-1.5.0.jar/net.square.sierra.packetevents.api.injector.ha

**Comment by TDMidkwhatisxd** [comment]
its packetevents issue or sierra issue? :D

**Comment by SquareCodeFX** [comment]
Server Version, Server Brand? Type /Version on the Server.

**Comment by SquareCodeFX** [comment]
I dont know if packetevents is supporting 1.21.1 atm

**Comment by TDMidkwhatisxd** [comment]
i think they do, with latest dev build, since i see pull request with 1.21.2  :)

**Comment by SquareCodeFX** [comment]
This release published 1.21 support: https://github.com/retrooper/packetevents/releases/tag/v2.4.0
So the rest of it is just a commit. Nothing release ready

**Comment by TDMidkwhatisxd** [comment]
https://github.com/retrooper/packetevents/issues/984

it say that your plugin does some non fuctioning stuff

**Comment by SquareCodeFX** [comment]
I will look into it later.

**Comment by SquareCodeFX** [comment]
https://github.com/Interlink-Media/Sierra/releases/tag/1.5.1
