### ISSUE TITLE
Async task for Sierra v1.3.3 generated an exception

### ISSUE THREAD

**Issue by wakatel** [Interlink-Media/Sierra#7]
**Description**
[Sierra] Async task for Sierra v1.3.3 generated an exception
java.lang.NullPointerException: Cannot invoke "de.feelix.sierra.manager.storage.SierraDataManager.getPlayerData()" because the return value of "de.feelix.sierra.manager.storage.SierraDataManager.getInstance()" is null
        at de.feelix.sierra.manager.init.impl.start.Ticker.lambda$start$1(Ticker.java:53) ~[Sierra-1.3.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.4.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
**Steps to reproduce**
Using Folia version git-Folia-"8210085" (MC: 1.20.4)
**Sierra Version**
1.3.3

**Comment by SquareCodeFX** [comment]
I will take a look at it in a few hours. I'm going to sleep now

**Comment by SquareCodeFX** [comment]
Thank you for reporting this issue. I was able to identify and fix it. Your error will be resolved in the new release version. Until then, you can ignore it as it only appears briefly at the beginning.
